#!/bin/bash

# Quick NPM Fix for DMGT Basic Form Deployment
# Run this before deployment to fix npm dependencies

set -e

echo "🔧 Quick NPM Fix for DMGT Basic Form"
echo "===================================="

# Navigate to frontend directory
cd frontend

echo "📊 Current environment:"
echo "Node.js: $(node --version)"
echo "npm: $(npm --version)"
echo "Working directory: $(pwd)"

echo ""
echo "🧹 Step 1: Cleaning up..."
rm -rf node_modules package-lock.json
npm cache clean --force

echo ""
echo "⚙️ Step 2: Creating .npmrc..."
cat > .npmrc << 'EOF'
legacy-peer-deps=true
fund=false
audit=false
progress=false
save-exact=true
engine-strict=false
EOF

echo ""
echo "📥 Step 3: Installing dependencies with legacy peer deps..."
npm install --legacy-peer-deps --no-audit --no-fund

echo ""
echo "🧪 Step 4: Testing build..."
echo "# Generated by DMGT deployment script on $(date)" > .env.production
echo "REACT_APP_API_URL=https://hfrcfsq0v6.execute-api.eu-west-2.amazonaws.com/dev" >> .env.production
echo "GENERATE_SOURCEMAP=false" >> .env.production

if npm run build; then
    echo ""
    echo "✅ SUCCESS! Dependencies are fixed and build is working!"
    echo "📁 Build size: $(du -sh build | cut -f1)"
    echo ""
    echo "🚀 Now you can deploy with:"
    echo "   cd .."
    echo "   ./deploy.sh --environment=dev --frontend-only"
else
    echo ""
    echo "❌ Build failed. Check the error messages above."
    exit 1
fi